language: php

php:
  - 7.2

cache:
  directories:
    - .composer/cache

matrix:
  fast_finish: true

install:
  - travis_retry composer update --no-progress --profile --no-scripts --no-suggest

script:
   - ./vendor/bin/grumphp run
